In [15]:
import re
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
pd.set_option("display.max_colwidth",200)

In [16]:
questions_df=pd.read_csv(r"C:\Users\shrishti\Videos\Captures\Auto stack exchange\Module 13\Questions.csv", encoding="Latin-1")
print("shape=>",questions_df.shape)
questions_df.head()

shape=> (85085, 6)


,Id,OwnerUserId,CreationDate,Score,Title,Body
0,6,5.0,2010-07-19T19:14:44Z,272,The Two Cultures: statistics vs. machine learning?,"<p>Last year, I read a blog post from <a href=""http://anyall.org/"">Brendan O'Connor</a> entitled <a href=""http://anyall.org/blog/2008/12/statistics-vs-machine-learning-fight/"">""Statistics vs. Mach..."
1,21,59.0,2010-07-19T19:24:36Z,4,Forecasting demographic census,<p>What are some of the ways to forecast demographic census with some validation and calibration techniques?</p>\n\n<p>Some of the concerns:</p>\n\n<ul>\n<li>Census blocks vary in sizes as rural\n...
2,22,66.0,2010-07-19T19:25:39Z,208,Bayesian and frequentist reasoning in plain English,<p>How would you describe in plain English the characteristics that distinguish Bayesian from Frequentist reasoning?</p>\n
3,31,13.0,2010-07-19T19:28:44Z,138,What is the meaning of p values and t values in statistical tests?,"<p>After taking a statistics course and then trying to help fellow students, I noticed one subject that inspires much head-desk banging is interpreting the results of statistical hypothesis tests...."
4,36,8.0,2010-07-19T19:31:47Z,58,Examples for teaching: Correlation does not mean causation,"<p>There is an old saying: ""Correlation does not mean causation"". When I teach, I tend to use the following standard examples to illustrate this point:</p>\n\n<ol>\n<li>number of storks and birth ..."


In [17]:
tags_df=pd.read_csv(r"C:\Users\shrishti\Videos\Captures\Auto stack exchange\Module 13\Tags.csv", encoding="Latin-1")
print("shape=>",tags_df.shape)
tags_df.head()

shape=> (244228, 2)


,Id,Tag
0,1,bayesian
1,1,prior
2,1,elicitation
3,2,distributions
4,2,normality


In [18]:
import re

def basic_clean(text):
    text = re.sub(r"<.*?>", " ", text)   # remove HTML tags (FAST)
    text = re.sub("[^a-zA-Z]", " ", text)
    text = text.lower()
    text = re.sub(r"\s+", " ", text)
    return text

questions_df["cleaned_text"] = questions_df["Body"].fillna("").apply(basic_clean)

In [19]:
questions_df["Body"][1]

"<p>What are some of the ways to forecast demographic census with some validation and calibration techniques?</p>\n\n<p>Some of the concerns:</p>\n\n<ul>\n<li>Census blocks vary in sizes as rural\nareas are a lot larger than condensed\nurban areas. Is there a need to account for the area size difference?</li>\n<li>if let's say I have census data\ndating back to 4 - 5 census periods,\nhow far can i forecast it into the\nfuture?</li>\n<li>if some of the census zone change\nlightly in boundaries, how can i\naccount for that change?</li>\n<li>What are the methods to validate\ncensus forecasts? for example, if i\nhave data for existing 5 census\nperiods, should I model the first 3\nand test it on the latter two? or is\nthere another way?</li>\n<li>what's the state of practice in\nforecasting census data, and what are\nsome of the state of the art methods?</li>\n</ul>\n"

In [20]:
questions_df["cleaned_text"][1]

' what are some of the ways to forecast demographic census with some validation and calibration techniques some of the concerns census blocks vary in sizes as rural areas are a lot larger than condensed urban areas is there a need to account for the area size difference if let s say i have census data dating back to census periods how far can i forecast it into the future if some of the census zone change lightly in boundaries how can i account for that change what are the methods to validate census forecasts for example if i have data for existing census periods should i model the first and test it on the latter two or is there another way what s the state of practice in forecasting census data and what are some of the state of the art methods '

In [21]:
tags_df.head()

,Id,Tag
0,1,bayesian
1,1,prior
2,1,elicitation
3,2,distributions
4,2,normality


In [22]:
len(tags_df["Tag"].unique())

1315

In [23]:
tags_df["Tag"].value_counts()

Tag
r                       13236
regression              10959
machine-learning         6089
time-series              5559
probability              4217
                        ...  
fmincon                     1
doc2vec                     1
sympy                       1
adversarial-boosting        1
corpus-linguistics          1
Name: count, Length: 1315, dtype: int64

In [24]:
tags_df["Tag"]=tags_df["Tag"].apply(lambda x: re.sub("-", " ", x))

In [25]:
tags_df=tags_df.groupby('Id').apply(lambda x:x['Tag'].values).reset_index(name='tags')

C:\Users\shrishti\AppData\Local\Temp\ipykernel_11856\105671489.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tags_df=tags_df.groupby('Id').apply(lambda x:x['Tag'].values).reset_index(name='tags')


In [26]:
tags_df.head()

,Id,tags
0,1,"[bayesian, prior, elicitation]"
1,2,"[distributions, normality]"
2,3,"[software, open source]"
3,4,"[distributions, statistical significance]"
4,6,[machine learning]


In [27]:
df=pd.merge(questions_df, tags_df, how='inner',on='Id')

In [28]:
df=df[['Id','Body','cleaned_text','tags']]
print("shape=>", df.shape)
df.head()

shape=> (85085, 4)


,Id,Body,cleaned_text,tags
0,6,"<p>Last year, I read a blog post from <a href=""http://anyall.org/"">Brendan O'Connor</a> entitled <a href=""http://anyall.org/blog/2008/12/statistics-vs-machine-learning-fight/"">""Statistics vs. Mach...",last year i read a blog post from brendan o connor entitled statistics vs machine learning fight that discussed some of the differences between the two fields andrew gelman responded favorably to...,[machine learning]
1,21,<p>What are some of the ways to forecast demographic census with some validation and calibration techniques?</p>\n\n<p>Some of the concerns:</p>\n\n<ul>\n<li>Census blocks vary in sizes as rural\n...,what are some of the ways to forecast demographic census with some validation and calibration techniques some of the concerns census blocks vary in sizes as rural areas are a lot larger than cond...,"[forecasting, population, census]"
2,22,<p>How would you describe in plain English the characteristics that distinguish Bayesian from Frequentist reasoning?</p>\n,how would you describe in plain english the characteristics that distinguish bayesian from frequentist reasoning,"[bayesian, frequentist]"
3,31,"<p>After taking a statistics course and then trying to help fellow students, I noticed one subject that inspires much head-desk banging is interpreting the results of statistical hypothesis tests....",after taking a statistics course and then trying to help fellow students i noticed one subject that inspires much head desk banging is interpreting the results of statistical hypothesis tests it ...,"[hypothesis testing, t test, p value, interpretation, intuition]"
4,36,"<p>There is an old saying: ""Correlation does not mean causation"". When I teach, I tend to use the following standard examples to illustrate this point:</p>\n\n<ol>\n<li>number of storks and birth ...",there is an old saying correlation does not mean causation when i teach i tend to use the following standard examples to illustrate this point number of storks and birth rate in denmark number of...,"[correlation, teaching]"


In [29]:
freq={}
for i in df['tags']:
    for j in i:
        if j in freq.keys():
          freq[j]=freq[j]+1
        else:
            freq[j]=1

In [30]:
freq=dict(sorted(freq.items(), key=lambda x:x[1],reverse=True))

In [31]:
freq.items()

dict_items([('r', 13236), ('regression', 10959), ('machine learning', 6089), ('time series', 5559), ('probability', 4217), ('hypothesis testing', 3869), ('self study', 3732), ('distributions', 3501), ('logistic', 3316), ('classification', 2881), ('correlation', 2871), ('statistical significance', 2666), ('bayesian', 2656), ('anova', 2505), ('normal distribution', 2181), ('multiple regression', 2054), ('mixed model', 1998), ('clustering', 1952), ('neural networks', 1897), ('mathematical statistics', 1888), ('confidence interval', 1776), ('categorical data', 1703), ('generalized linear model', 1614), ('variance', 1576), ('data visualization', 1549), ('estimation', 1533), ('forecasting', 1422), ('t test', 1418), ('pca', 1395), ('sampling', 1363), ('cross validation', 1344), ('repeated measures', 1335), ('spss', 1296), ('svm', 1283), ('chi squared', 1261), ('maximum likelihood', 1209), ('predictive models', 1189), ('multivariate analysis', 1116), ('survival', 1081), ('references', 1076), (

In [32]:
common_tags=list(freq.keys())[:10]
common_tags

['r',
 'regression',
 'machine learning',
 'time series',
 'probability',
 'hypothesis testing',
 'self study',
 'distributions',
 'logistic',
 'classification']

In [33]:
x=[]
y=[]

for i in range(len(df['tags'])):
    temp=[]
    for j in df['tags'][i]:
        if j in common_tags:
          temp.append(j)   
    if (len(temp)>1):
        x.append(df['cleaned_text'][i])
        y.append(temp)

In [34]:
len(x)

11106

In [35]:
x[:5]

[' i recently started working for a tuberculosis clinic we meet periodically to discuss the number of tb cases we re currently treating the number of tests administered etc i d like to start modeling these counts so that we re not just guessing whether something is unusual or not unfortunately i ve had very little training in time series and most of my exposure has been to models for very continuous data stock prices or very large numbers of counts influenza but we deal with cases per month mean median var which are distributed like this image lost to the mists of time image eaten by a grue i ve found a few articles that address models like this but i d greatly appreciate hearing suggestions from you both for approaches and for r packages that i could use to implement those approaches edit mbq s answer has forced me to think more carefully about what i m asking here i got too hung up on the monthly counts and lost the actual focus of the question what i d like to know is does the fairl

In [36]:
y[:5]

[['r', 'time series'],
 ['regression', 'distributions'],
 ['distributions', 'probability', 'hypothesis testing'],
 ['hypothesis testing', 'self study'],
 ['r', 'regression', 'time series']]

In [37]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb=MultiLabelBinarizer()
y=mlb.fit_transform(y)
y.shape

(11106, 10)

In [38]:
y[0,:]

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [39]:
mlb.classes_

array(['classification', 'distributions', 'hypothesis testing',
       'logistic', 'machine learning', 'probability', 'r', 'regression',
       'self study', 'time series'], dtype=object)

In [40]:
from sklearn.model_selection import train_test_split
x_tr,x_val,y_tr,y_val=train_test_split(x,y,test_size=0.2,random_state=0, shuffle=True)

In [41]:
print("x_tr:", len(x_tr), "y_tr:", len(y_tr))
print("x_val:",len(x_val), "y_val:", len(y_val))

x_tr: 8884 y_tr: 8884
x_val: 2222 y_val: 2222


In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [43]:
word_vectorizer=TfidfVectorizer(max_features=5000)

In [44]:
word_vectorizer.fit(x_tr)

,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None
,analyzer,'word'
,stop_words,None
,token_pattern,'(?u)\\b\\w\\w+\\b'
,ngram_range,"(1, ...)"


In [45]:
train_word_features=word_vectorizer.transform(x_tr)

In [46]:
train_word_features

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 689105 stored elements and shape (8884, 5000)>

In [47]:
test_word_features=word_vectorizer.transform(x_val)
test_word_features

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 169720 stored elements and shape (2222, 5000)>

In [48]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import f1_score

In [49]:
nb_model=OneVsRestClassifier(MultinomialNB())

In [50]:
nb_model.fit(train_word_features,y_tr)

,estimator,MultinomialNB()
,n_jobs,None
,verbose,0
,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [71]:
train_pred_nb = nb_model.predict_proba(train_word_features)

In [73]:
train_pred_nb[:5]

array([[0.01344724, 0.03740482, 0.28222978, 0.02697458, 0.01633795,
        0.02506567, 0.89538969, 0.12073754, 0.0700849 , 0.9171051 ],
       [0.00998546, 0.0110149 , 0.02463366, 0.07908787, 0.02420268,
        0.01546075, 0.42975165, 0.6741038 , 0.01497687, 0.39696457],
       [0.06333453, 0.02789201, 0.0424841 , 0.2655143 , 0.09664726,
        0.0317234 , 0.34204464, 0.59332859, 0.04190282, 0.0376353 ],
       [0.0256477 , 0.02181011, 0.06350088, 0.04377451, 0.08734494,
        0.01908054, 0.58005273, 0.35855072, 0.05014792, 0.58172381],
       [0.00645846, 0.0017878 , 0.00359254, 0.00911818, 0.03907929,
        0.00232402, 0.92296367, 0.16261188, 0.00382148, 0.98254765]])

In [77]:
def classify(pred_prob, threshold):
    return (pred_prob >= threshold).astype(int)

In [78]:
import numpy as np
from sklearn.metrics import f1_score

def optimum_threshold(actual, pred_prob):
    thresholds = np.arange(0, 0.5, 0.1)  # from 0 to 0.5

    score = []
    
    for value in thresholds:
        pred_classes = classify(pred_prob, value)
        score.append(f1_score(actual, pred_classes, average="weighted"))
        
    return thresholds[score.index(max(score))]

In [79]:
print("Optimal Threshold=>", optimum_threshold(y_tr, train_pred_nb))

Optimal Threshold=> 0.30000000000000004


In [80]:
train_pred_nb_class=classify(train_pred_nb, 0.30)

In [81]:
train_pred_nb_class[:5]

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1]])

In [83]:
mlb.inverse_transform(np.array(train_pred_nb_class[:5]))

[('r', 'time series'),
 ('r', 'regression', 'time series'),
 ('r', 'regression'),
 ('r', 'regression', 'time series'),
 ('r', 'time series')]

In [86]:
print("f1-score on train-set:",f1_score(y_tr,train_pred_nb_class,average="weighted"))

f1-score on train-set: 0.7173779844739174


In [87]:
val_pred_nb=nb_model.predict_proba(test_word_features)

In [88]:
val_pred_nb_class=classify(val_pred_nb,0.30)

In [89]:
print("f1-score on validation set:", f1_score(y_val,val_pred_nb_class, average="weighted"))

f1-score on validation set: 0.6471715961995358


In [90]:
from sklearn.linear_model import LogisticRegression

In [93]:
lr_model=OneVsRestClassifier(LogisticRegression())
lr_model.fit(train_word_features, y_tr)

,estimator,LogisticRegression()
,n_jobs,None
,verbose,0
,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None


In [95]:
train_pred_lr=lr_model.predict_proba(train_word_features)

In [96]:
train_pred_lr[:5]

array([[0.019655  , 0.03355877, 0.27107585, 0.03275855, 0.02303131,
        0.02489797, 0.90555739, 0.12760037, 0.04931186, 0.65955848],
       [0.02274497, 0.03116318, 0.09357807, 0.08456416, 0.03927476,
        0.03656584, 0.4139801 , 0.85330895, 0.05036709, 0.50195913],
       [0.07891207, 0.02846155, 0.04503306, 0.24182428, 0.10834637,
        0.03246708, 0.63254943, 0.81833722, 0.04548671, 0.0651938 ],
       [0.01567344, 0.01305426, 0.40801349, 0.0418786 , 0.08837533,
        0.0058441 , 0.64418692, 0.41407137, 0.03528106, 0.58271905],
       [0.0308317 , 0.00683419, 0.01773856, 0.03878678, 0.08578545,
        0.00753684, 0.9235889 , 0.24798212, 0.01633365, 0.93859518]])

In [97]:
print("Optimal Threshold=>", optimum_threshold(y_tr,train_pred_lr))

Optimal Threshold=> 0.30000000000000004


In [98]:
train_pred_lr_class=classify(train_pred_lr,0.300004)

In [99]:
train_pred_lr_class[:5]

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1]])

In [101]:
print("F1-score on train set:", f1_score(y_tr, train_pred_lr_class,average="weighted"))

F1-score on train set: 0.8244114965777203


In [105]:
val_pred_lr=lr_model.predict_proba(test_word_features)

In [106]:
val_pred_lr_class=classify(val_pred_lr,0.30)

In [107]:
print("F1-score on Validation set:", f1_score(y_val,val_pred_lr_class,average="weighted"))

F1-score on Validation set: 0.7536380833989702


In [113]:
def tagging(question):
    cleaned_question=basic_clean(question)
    vector=word_vectorizer.transform([cleaned_question])
    pred_prob=lr_model.predict_proba(vector)
    pred_class=classify(pred_prob,0.300004)

    return mlb.inverse_transform(np.array(pred_class))
    

In [120]:
import numpy as np
all_tags = mlb.classes_
def tagging(question, top_k=3):
    cleaned_question = basic_clean(question)

    vector = word_vectorizer.transform([cleaned_question])
    pred_prob = lr_model.predict_proba(vector)

    probs = pred_prob[0]

    top_indices = np.argsort(probs)[-top_k:]
    tags = [all_tags[i] for i in top_indices]

    return tags

In [124]:
tagging("<p>How would you describe in plain English the characteristics that distinguish Bayesian from Frequentist reasoning?</p>\n")

['r', 'self study', 'probability']

In [125]:
import pickle

pickle.dump(lr_model, open("lr_model.pkl", "wb"))
pickle.dump(word_vectorizer, open("vectorizer.pkl", "wb"))
pickle.dump(mlb, open("mlb.pkl", "wb"))